import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import dynamic from "next/dynamic";
import { Poppins } from "next/font/google";
import { CartProvider } from "@/context/CartContext";
import { FavoritesProvider } from "@/context/FavoritesContext"; // ✅ added
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";

const Navbar = React.lazy(() => import("@/components/Navbar"));
const Footer = React.lazy(() => import("@/components/Footer"));

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
  display: "swap",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "LK-Collection",
  description: "Generated by create next app",
   icons: {
    icon: "images/logo1.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased`}
        >
          {/* ✅ Wrap everything inside both providers */}
          <FavoritesProvider>
            <CartProvider>
              <Navbar />
              {children}
              <Footer />
            </CartProvider>
          </FavoritesProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
